//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proc_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class action_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public action_tbl()
        {
            this.bets_tbl = new HashSet<bets_tbl>();
        }
    
        public int ActionID { get; set; }
        public string ActionDescription { get; set; }
        public Nullable<decimal> Odds { get; set; }
        public Nullable<int> EventID { get; set; }
    
        public virtual event_tbl event_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bets_tbl> bets_tbl { get; set; }
    }
}
