//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proc_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class bets_tbl
    {
        public int BetID { get; set; }
        public int ActionID { get; set; }
        public int MemberID { get; set; }
        public Nullable<decimal> BetAmount { get; set; }
        public Nullable<System.DateTime> BetDate { get; set; }
        public Nullable<decimal> Odds { get; set; }
    
        public virtual action_tbl action_tbl { get; set; }
        public virtual member_tbl member_tbl { get; set; }
    }
}
