//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proc_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class wallet_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wallet_tbl()
        {
            this.transaction_tbl = new HashSet<transaction_tbl>();
        }
    
        public int WalletID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<decimal> Balance { get; set; }
    
        public virtual member_tbl member_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction_tbl> transaction_tbl { get; set; }
    }
}
